### ISSUE TITLE
Move to org ?

### ISSUE THREAD

**Issue by srush** [chalk-diagrams/chalk#103]
Plan? 

- [x] move code base to the new org.
- [x] move GitHub pages to chalk-diagrams.github.io
- [x] move planar codebase over as well.
- [x] start tagging versions / pypi

Would be nice not to lose history if possible.

**Comment by danoneata** [comment]
Yes, that sounds like a good plan! I would hope that the history is preserved; [it seems](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository#whats-transferred-with-a-repository) that much of the other information (issues, pull requests, wiki, stars, watchers) is transferred.

**Comment by danoneata** [comment]
Sorry, I've messed up the repository trying to compile the documentation. I've ran
```bash
mkdocs gh-deploy
```
and it pushed the documentation to this repository, although I thought it would use the documentation repository; this is the current the `mkdocs.yml` configuration file:
```
repo_url: https://github.com/chalk-diagrams/chalk-diagrams.github.io
remote_branch: master
remote_name: origin
```
Do you know how the `mkdocs` config file should be modified?

Also I've noticed that the Github documentation workflow fails, although I'm not sure why; on my machine it runs successfully, so it might be due to some different versions of some of the packages?

**Comment by danoneata** [comment]
Thanks for the hint! In the end I've used
```bash
mkdocs build --config-file mkdocs.yml --site-dir ../chalk-diagrams.github.io
```
since running `mkdocs` from a different directory failed (because many of the paths are relative to the project's root).

Next I'll go through the documentation to clean up the errors that pop up there and then release a new version on pypi.

**Comment by srush** [comment]
Cool. Feel free to rearrange docs or add more examples. It's kind of out of date. I probably also broke my clock example.

**Comment by danoneata** [comment]
Yup! I'll fix the clock example, no worries!

**Comment by danoneata** [comment]
Hello! I've created a new release on both [Github](https://github.com/chalk-diagrams/chalk/releases/tag/v0.2.1) and [PyPI](https://test.pypi.org/project/chalk-diagrams/0.2.1/), so I think this issue can be closed.
